import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Navbar from '@/components/Navbar';
import { Toaster } from 'react-hot-toast';
import { usePathname } from 'next/navigation';
const inter = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'ReadyUp',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={inter.className}>
					<Toaster />
					<Navbar />
					<div className='px-2'>{children}</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
